version: '3'

services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass

  bot:
    build: ./
    command: bash -c "python bot.py"
    volumes:
      - .:/bot:rw
    depends_on:
      - mongo
    environment:
      MONGO_USERNAME: user
      MONGO_PASSWORD: pass
